name: LocalGov Drupal Starter
type: Site
description: A simple template with just the basics. Bring your own design, and build what you need.
recipes:
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
  - core/recipes/document_media_type
  - core/recipes/image_media_type
  - core/recipes/remote_video_media_type
install:
  # Core
  - block
  - ckeditor5
  - config
  - editor
  - filter
  - field
  - help
  - link
  - media
  - media_library
  - node
  - views
  - toolbar
  - token
  - menu_link_content
  - update
  # The rest of these are in Standard.
  - inline_form_errors
  - config
  - help
  - views_ui
  # Install Claro as it is a dependency of Gin, but don't import config.
  - claro
  # Install Toolbar as it is a dependency of Gin Toolbar.
  - toolbar
  - admin_toolbar
  - admin_toolbar_tools
  # Install Gin theme and base modules that extend it.
  - gin
  - gin_login
  - gin_toolbar
  - entity_browser
  - linkit
  - pathauto
  - paragraphs
  - paragraphs_library
  - preview_link
  - simple_sitemap
  - redirect
  # LocalGov Drupal
  - localgov_base
  - localgov_scarfolk
  - localgov_admin_role
  - localgov_admin_theme_improvements
  - localgov_core
  - localgov_login_redirect
  - localgov_media
  - localgov_menu_link_group
  - localgov_page_components
  - localgov_paragraphs
  - localgov_roles
  - localgov_topics
  - localgov_services
  - localgov_services_landing
  - localgov_services_navigation
  - localgov_services_page
  - localgov_services_sublanding
config:
  # If the config we're importing already exists, we don't really care
  # what it looks like.
  strict: false
  import:
    node: '*'
    admin_toolbar: '*'
    admin_toolbar_tools: '*'
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_help
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
    gin_login: '*'
    entity_browser: '*'
    linkit: '*'
    paragraphs: '*'
    paragraphs_library: '*'
    preview_link: '*'
    simple_sitemap: '*'
    redirect: '*'
    localgov_base: '*'
    localgov_scarfolk: '*'
    localgov_admin_theme_improvements: '*'
    localgov_core: '*'
    localgov_login_redirect: '*'
    localgov_media: '*'
    localgov_menu_link_group: '*'
    localgov_page_components: '*'
    localgov_paragraphs: '*'
    localgov_roles: '*'
    localgov_topics: '*'
    localgov_services: '*'
    localgov_services_landing: '*'
    localgov_services_navigation: '*'
    localgov_services_page: '*'
    localgov_services_sublanding: '*'
  actions:
    # Set and unset Gin blocks.
    # block.block.gin_admin:
    #   simpleConfigUpdate:
    #     status: false
    # block.block.gin_branding:
    #   simpleConfigUpdate:
    #     status: false
    # block.block.gin_local_actions:
    #   simpleConfigUpdate:
    #     region: content
    #     weight: -10
    # block.block.gin_local_tasks:
    #   simpleConfigUpdate:
    #     status: false
    # block.block.gin_page_title:
    #   simpleConfigUpdate:
    #     region: header
    #     weight: -10
    # block.block.gin_primary_local_tasks:
    #   simpleConfigUpdate:
    #     region: header
    #     weight: -5
    #     settings.secondary: true
    # block.block.gin_tools:
    #   simpleConfigUpdate:
    #     status: false
    # Update the admin theme to Gin in Theme settings.
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    gin.settings:
      simpleConfigUpdate:
        classic_toolbar: horizontal
    system.theme:
      simpleConfigUpdate:
        admin: gin
        default: localgov_scarfolk
    # Update core date settings
    core.date_format.long:
      simpleConfigUpdate:
        pattern: 'l j F Y \a\t g:ia'
    core.date_format.medium:
      simpleConfigUpdate:
        pattern: 'D d/m/Y g:ia'
    core.date_format.short:
      simpleConfigUpdate:
        pattern: 'd/m/Y g:ia'
    user.role.localgov_admin:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: localgov_admin
        label: LocalGov Admin
        is_admin: true
extra:
  recipe_installer_kit:
    finish_url: '/'
